package com.streetify.factory;

/**
 * AdminActionType — Enum for Admin Action Types (GoF Factory Pattern)
 *
 * ─────────────────────────────────────────────────────────────────
 * Pattern   : Factory (Creational)
 * Member    : Vidura (IT25102240) — Admin Governance & System Control
 * Role      : Replaces all magic action type strings
 * ─────────────────────────────────────────────────────────────────
 *
 * Defines all known admin action types that AuditLogFactory
 * can create AuditLog objects for.
 *
 * BEFORE (problem — magic strings scattered in AdminGovernanceService):
 *   writeAuditLog(adminId, adminEmail, "ACCOUNT_SUSPENDED", ...);
 *   writeAuditLog(adminId, adminEmail, "ACCOUNT_UNSUSPENDED", ...);
 *   // No compile-time safety — typos allowed, inconsistent strings
 *
 * AFTER (Factory Pattern with this enum):
 *   AuditLogFactory.create(AdminActionType.ACCOUNT_SUSPENDED, ...);
 *   // Compile-time safety — typos caught immediately
 *
 * Lecture Reference (Lecture A, Slide 32):
 *   "Create a Factory Class — the client (AdminGovernanceService)
 *    uses an action type to request the correct object from the factory."
 */
public enum AdminActionType {

    /** A user account has been suspended by an admin/staff */
    ACCOUNT_SUSPENDED,

    /** A previously suspended user's account has been reinstated */
    ACCOUNT_UNSUSPENDED,

    /** All required driver documents have been approved by staff */
    DRIVER_VERIFICATION_APPROVED,

    /** One or more driver documents were rejected by staff */
    DRIVER_VERIFICATION_REJECTED,

    /** A single driver document was reviewed (approved or rejected) */
    DRIVER_DOCUMENT_REVIEWED,

    /** A revenue report was generated by an admin */
    REVENUE_REPORT_GENERATED,

    /** A dispute ticket was resolved by staff */
    DISPUTE_RESOLVED,

    /** A dispute refund was approved and applied to passenger wallet */
    DISPUTE_REFUND_APPROVED
}
